# Generated by Django 3.1.6 on 2021-02-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_create'),
        ('api', '0002_delete_test'),
    ]

    operations = [
    ]
