# Generated by Django 3.1.6 on 2021-03-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210314_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('40 X 60', '40 X 60'), ('100 X 200', '100 X 200'), ('200 X 300', '200 X 300')], max_length=155, null=True),
        ),
    ]
